# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0823e7f2f3477475086a18b1fe88a7a366a33dc001fe77774e85662a444a544adf9330d721771c5387f8527f788d9de188c62d3600243fe072f298e93a9bbe31

test:
  secret_key_base: 616291c3dc3f83b4550da1e2459377c6ab323897624066d2883281e7d768d1ab750c572d3d17135bfb4f380c254aee79e985e7702816829eda688a2f228b9096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
